export type { IconProps, AnimationSpeed } from './types/IconProps';
export { DURATION, EASING_CSS } from './tokens/timing';
export type { DurationSet } from './tokens/timing';
export * from './paths/ui';
export * from './paths/healthcare';
export * from './paths/actions';
export * from './paths/communication';
export * from './paths/settings';
export * from './paths/files';
export * from './paths/media';
export * from './paths/device';
